---
title: "US States Cases and Death Total"
author: "David J Jackson"
date: "5/19/2020 3:15 PM/EDT"
output: html_document 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.width=9, fig.height=6)
library(tidyverse)
library(RSQLite)
library(plotly)
theme_set(theme_light())
```
```{r echo=FALSE}
rm(list=ls())
db <- dbConnect(SQLite(), dbname="../COVIDDB/CORVID.sqlite3")
STATES <- dbGetQuery(db, "SELECT * FROM STATESDAILY ;")
```
```{r echo=FALSE}
STATESSUM <- STATES %>% group_by(state) %>%
  summarise(tc = sum(new_cases),
                     td = sum(new_deaths))
```

### Total Cases and Deaths for all 50 states .

```{r echo=FALSE}
plot1 <-ggplot(STATESSUM) + geom_point(aes(x=tc,y=state,size=tc,col=tc)) +
   scale_x_continuous(labels = scales::comma) +
  labs(title="Total Cases by States",subtitle="(As of May 19, 2020)",
       x="Total Cases",y="US States") + geom_vline(xintercept =27156    ) +
  geom_abline(color="red") 

plot2 <- ggplot(STATESSUM) + geom_point(aes(x=td,y=state,size=tc,col=td)) +
   scale_x_continuous(labels = scales::comma) +
  labs(title="Total Deaths by States",subtitle="(As of May 19, 2020)",
       x="Total Deaths",y="US States") + geom_vline(xintercept = 1627) +
    geom_abline(color="red")
ggplotly(plot1)
ggplotly(plot2)
```
Total Cases and Deaths for 48 States (No NY or NJ) and 
```{r}
NONYNJ <- STATESSUM %>% filter(state !="New York",state !="New Jersey")

plot3 <-ggplot(NONYNJ) + geom_point(aes(x=tc,y=state,size=tc,col=tc)) +
   scale_x_continuous(labels = scales::comma) +
  labs(title="Total Cases by States( w/o NY or NJ)",
       x="Total Cases",y="US States") + geom_vline(xintercept =18720    )

plot3 <- ggplot(NONYNJ) + geom_point(aes(x=td,y=state,size=tc,col=tc)) +
   scale_x_continuous(labels = scales::comma) +
  labs(title="Total Deaths by States (No NY or NJ",
       x="Total Deaths",y="US States") + geom_vline(xintercept = 961) 
ggplotly(plot3)
ggplotly(plot3)
```
